# Welcome to Serverless!
#
# For full config options, check the docs:
#    docs.serverless.com

service: swiftshop-api
# app and org for use with dashboard.serverless.com
app: swiftshop-api-app
org: apiapkdev

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:PutItem
        #- SES:*
      Resource: "arn:aws:dynamodb:us-east-1:*:table/users"

functions:
  createUser:
    handler: handler.handler
    events:
     - httpApi:
        path: /user
        method: post
        cors: true

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
          TableName: users
          AttributeDefinitions:
            - AttributeName: email
              AttributeType: S
          KeySchema:
            - AttributeName: email
              KeyType: HASH
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1

